{% set name = "scrubadub" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LeapBeyond/scrubadub/archive/v{{ version }}.tar.gz
  sha256: 43652270d9e808318bf1741ddeb08a9dea30a91d28f3a3963041f30be9fc8d25
  patches:
    - patches/0001-changed-textblob-pin.patch
    - patches/0002-disable-pep-warnings.patch
    # There are 7 different tests with the same name. Disabled by patch.
    - patches/0003-disable-test.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # The textblob pkg is not available on s390x target
  skip: True  # [s390x]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    # The conda main + snowflake channels have only 0.17.1 and 0.18.0.post0 versions.
    - textblob <=0.18.0.post0
    - phonenumbers
    - python-stdnum
    - dateparser
    - catalogue
    - scikit-learn
    - typing-extensions
    - faker

# tests/test_comparison_classes.py::ComparisonTestCase::test_filth_grouper
# AssertionError: Lists differ: [('name', 'tagged', 'en_US'), ('phone', 'pho[98 chars]US')] != [('phone', 'phone', 'en_GB'), ('phone', 'tag[98 chars]US')]

# tests/test_comparison.py::ComparisonTestCase::test_dataframe
# AssertionError: Lists differ: ['phone', 'phone', 'none', 'none'] != ['phone', 'none', 'phone', 'none']

test:
  source_files:
    - tests
  imports:
    - scrubadub
  commands:
    - pip check
    # Test process described in the GHA workflow unittests.yaml :
    # https://github.com/LeapBeyond/scrubadub/blob/v2.0.1/.github/workflows/unittests.yml#L78
    # Needed for stanford model
    # Resource punkt_tab not found.
    # NLTK Downloader is used to obtain the resource:
      # >>> import nltk
      # >>> nltk.download('punkt_tab')
    - python -c "import nltk; nltk.download('punkt_tab')"
    # Benchmark tests:
    # ./tests/benchmark_accuracy.py --fast
    # ./tests/benchmark_time.py
    - python -v tests/run.py
    # Unit and Functional tests
    # test_filth_grouper and test_dataframe disabled by the logical errors.
    - pytest -v -k "not (test_filth_grouper or test_dataframe)" tests
  requires:
    - pip
    - pytest
    - pandas
    - requests
    - nltk
    - wasabi

about:
  home: https://github.com/LeapBeyond/scrubadub
  summary: Clean personally identifiable information from dirty dirty text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - snegireff
