{% set name = "scrubadub" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LeapBeyond/scrubadub/archive/v{{ version }}.tar.gz
  sha256: 43652270d9e808318bf1741ddeb08a9dea30a91d28f3a3963041f30be9fc8d25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python
    # The conda main or snowflake channel have only 0.17.1 and 0.18.0.post0
    - textblob >=0.15.3,<=0.18.0.post0
    - phonenumbers
    - python-stdnum
    - dateparser
    - catalogue
    - scikit-learn
    - typing-extensions
    - faker

test:
  source_files:
    - tests
  imports:
    - scrubadub
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/LeapBeyond/scrubadub
  summary: Clean personally identifiable information from dirty dirty text.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - snegireff
